spring.application.name=studygenie-ai

spring.datasource.url=jdbc:mysql://localhost:3306/studygenie
spring.datasource.username=root
spring.datasource.password=pinkglitter

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
